# Generated by Django 4.2.5 on 2023-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="high",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
