# Generated by Django 4.2.5 on 2023-09-29 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_band_like_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="like_news",
        ),
    ]
